# Generated by Django 6.0.7 on 2026-07-23 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('email_change', "Email o'zgartirish"), ('account_delete', "Hisobni o'chirish")], max_length=20)),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
